/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_android_keepalive_natives_NativeDaemonAPI21
#define _Included_com_android_keepalive_natives_NativeDaemonAPI21
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_android_keepalive_natives_NativeDaemonAPI21_doDaemon
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
